### ISSUE TITLE
Ratchet to Thruway conversion

### ISSUE THREAD

**Issue by xtrasmal** [voryx/Thruway#96]
Hi there,

The code below is what I use from the Ratchet website: http://socketo.me/docs/push
I've got it in a console command in my favorite framework and run it.
After that I can connect, publish and subscribe.

Ratchet has a very clear website that get's you on your way pretty fast.

But I've learned that Ratchet uses WAMP v1 and Thruway can help me up and running with WAMP v2 so I can use the latest Autobahn version and the angular-wamp router.
 
Could you please explain to me how I can get Thruway set up in the same way I've got Ratchet set up?
I'd like to start everything from one command.

PushServerCommand.php

```php

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function fire()
    {
        $loop   = EventloopFactory::create();
        $pusher = new Pusher;

        // Listen for the web server to make a ZeroMQ push after an ajax request
        $context = new Context($loop);
        $pull = $context->getSocket(\ZMQ::SOCKET_PULL);

        $pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
        $pull->on('message', [$pusher, 'onBlogEntry']);

        // Set up our WebSocket server for clients wanting real-time updates
        $webSock = new Server($loop);
        $webSock->listen(7474, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
        $webServer = new IoServer(
            new HttpServer(
                new WsServer(
                    new WampServer(
                        $pusher
                    )
                )
            ),
            $webSock
        );

        $loop->run();

    }

```
Pusher.php

```php

class Pusher implements WampServerInterface {
    /**
     * A lookup of all the topics clients have subscribed to
     */
    protected $subscribedTopics = array();

    public function onSubscribe(ConnectionInterface $conn, $topic) {
        $this->subscribedTopics[$topic->getId()] = $topic;
    }

    /**
     * @param string JSON'ified string we'll receive from ZeroMQ
     */
    public function onBlogEntry($entry) {
        $entryData = json_decode($entry, true);

        // If the lookup topic object isn't set there is no one to publish to
        if (!array_key_exists($entryData['category'], $this->subscribedTopics)) {
            return;
        }

        $topic = $this->subscribedTopics[$entryData['category']];

        // re-send the data to all the clients subscribed to that category
        $topic->broadcast($entryData);
    }

    /* The rest of our methods were as they were, omitted from docs to save space */
}

```

Thank you a lot.

**Comment by davidwdan** [comment]
This should accomplish the same thing.  One note is that with WAMPv2 you need to specify a realm in the router and clients.

PushServerCommand.php
```PHP

$router = new Router();
$realm = "realm1";

$router->addInternalClient(new Pusher($realm, $router->getLoop()));
$router->addTransportProvider(new RatchetTransportProvider("0.0.0.0", 7474));
$router->start();

```

Pusher.php

```PHP

class Pusher extends Thruway\Peer\Client
{
    public function onSessionStart($session, $transport)
    {

        $context = new React\ZMQ\Context($this->getLoop());
        $pull    = $context->getSocket(ZMQ::SOCKET_PULL);
        $pull->bind('tcp://127.0.0.1:5555');
        $pull->on('message', [$this, 'onBlogEntry']);

    }


    /**
     * @param string JSON'ified string we'll receive from ZeroMQ
     */
    public function onBlogEntry($entry)
    {

        $entryData = json_decode($entry, true);

        if (!isset($entryData['category'])) {
            return;
        }

        $this->getSession()->publish($entryData['category'], [$entryData]);

    }

}

```

**Comment by xtrasmal** [comment]
That is amazing. Thank you. I looked and looked and couldn't find any leads :+1: It seems like 
I was running version 0.2.* of this repo. It didn't have the addInternalClient method.

I'm happy as a 12 year old. Thank you very much.

**Comment by davidwdan** [comment]
I'm glad that's working for you.  You can further simplify that code by combining everything into one file and using the event emitter.  

How you do it is up to you, but I thought I'd add this just in case someone else needs it:

PushServerCommand.php

```PHP

$loop   = \React\EventLoop\Factory::create();
$pusher = new \Thruway\Peer\Client("realm1", $loop);

$pusher->on('open', function ($session) use ($loop) {
    $context = new React\ZMQ\Context($loop);
    $pull    = $context->getSocket(ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5555');

    $pull->on('message', function ($entry) use ($session) {
        $entryData = json_decode($entry, true);
        if (isset($entryData['category'])) {
            $session->publish($entryData['category'], [$entryData]);
        }
    });
});

$router = new Thruway\Peer\Router($loop);
$router->addInternalClient($pusher);
$router->addTransportProvider(new Thruway\Transport\RatchetTransportProvider("0.0.0.0", 7474));
$router->start();

```

**Comment by xtrasmal** [comment]
@davidwdan good to see more clear examples like that. I think that most users use Symfony or Laravel and start stuff through Cli commands or keep the commands running in the background through supervisord. 
That being said, I think that keeping everything seperated would be nicer to introduce more flexibilty. The Pusher might need some dependency injection or whatever.

**Comment by wkiril** [comment]
Hello @davidwdan,

I'm actually trying to do the same using your example but encounter an error:
```php
    public function fire()
    {
        $loop = React\EventLoop\Factory::create();

        $pusher = new Thruway\Peer\Client(Config::get('websocket.realm'), $loop);
        $pusher->on('open', function ($session) use ($loop) {
            $context = new React\ZMQ\Context($loop);
            $pull = $context->getSocket(ZMQ::SOCKET_PULL);
            $pull->bind(Config::get('websocket.zmq'));
            $pull->on('message', function ($message) use ($session) {
                $data = json_decode($message, true);
                if (isset($data['topic'])) {
                    $session->publish($data['topic'], [$data]);
                }
            });
        });

        $router = new Thruway\Peer\Router($loop);
        $router->addInternalClient($pusher);
        $router->addTransportProvider(
            new Thruway\Transport\RatchetTransportProvider(Config::get('websocket.ip'), Config::get('websocket.port'))
        );

        $router->start();
    }
```

and when I start it I get:
```
2015-07-07T17:40:29.5872580 notice     [Thruway\Peer\Client 6839] Changing PHP precision from 14 to 16
2015-07-07T17:40:29.5905730 info       [Thruway\Peer\Client 6839] New client created
2015-07-07T17:40:29.5943320 debug      [Thruway\Peer\Router 6839] New router created
2015-07-07T17:40:29.6116070 info       [Thruway\Peer\Router 6839] Starting router
2015-07-07T17:40:29.6130020 info       [Thruway\Peer\Router 6839] Starting transport provider Thruway\Transport\InternalClientTransportProvider
2015-07-07T17:40:29.6298760 info       [Thruway\Peer\Router 6839] New Session started {"type":"internalClient","transportAddress":"internal"}
2015-07-07T17:40:29.6423700 debug      [Thruway\RealmManager 6839] Creating new realm "taxi"
2015-07-07T17:40:29.6488310 debug      [Thruway\RealmManager 6839] Adding realm "taxi"
2015-07-07T17:40:29.6496600 info       [Thruway\RealmManager 6839] Realm "taxi" is using ManagerDummy
2015-07-07T17:40:29.6500550 debug      [Thruway\Realm 6839] Got Hello
2015-07-07T17:40:29.6602620 debug      [Thruway\Role\Broker 6839] Broker onMessage for {"type":"dummyTransport","transportAddress":"dummy"}: [16,2285617482499740,{},"wamp.metaevent.session.on_join",[{"realm":"taxi","authprovider":null,"authid":"anonymous","authrole":"anonymous","authroles":[],"authmethod":"anonymous","session":8971619779318486,"role_features":{"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true}},"subscriber":{"features":{}},"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"caller_identification":true,"progressive_call_results":true}}}}]]
2015-07-07T17:40:29.6623110 debug      [Thruway\Peer\Client 6839] Client onMessage: [Thruway\Message\WelcomeMessage]
2015-07-07T17:40:29.6629000 info       [Thruway\Peer\Client 6839] We have been welcomed...
                                                    
  [Exception]                                       
  Session::abort called after we are authenticated  
```

I'll appreciate it if you could help debug the issue

**Comment by davidwdan** [comment]
What are your PHP and Thruway versions?

**Comment by wkiril** [comment]
PHP 5.6.10
Thruway 0.3.8

**Comment by davidwdan** [comment]
I'm having trouble reproducing this.  Anyway you can get a stack trace?

**Comment by davidwdan** [comment]
I played around with this some more and the only way that I could reproduce your issue was by passing an empty string into the zmq bind method.  Can you try replacing ```Config::get('websocket.zmq')``` with the actual url and see if that works?

**Comment by wkiril** [comment]
replaced it with ```'tcp://127.0.0.1:5555'``` still the same error
here's the stack trace:
```
2015-07-08T09:40:52.8993740 notice     [Thruway\Peer\Client 7403] Changing PHP precision from 14 to 16
2015-07-08T09:40:52.9034790 info       [Thruway\Peer\Client 7403] New client created
2015-07-08T09:40:52.9092970 debug      [Thruway\Peer\Router 7403] New router created
2015-07-08T09:40:52.9219950 info       [Thruway\Peer\Router 7403] Starting router
2015-07-08T09:40:52.9234980 info       [Thruway\Peer\Router 7403] Starting transport provider Thruway\Transport\InternalClientTransportProvider
2015-07-08T09:40:52.9348990 info       [Thruway\Peer\Router 7403] New Session started {"type":"internalClient","transportAddress":"internal"}
2015-07-08T09:40:52.9439760 debug      [Thruway\RealmManager 7403] Creating new realm "taxi"
2015-07-08T09:40:52.9513830 debug      [Thruway\RealmManager 7403] Adding realm "taxi"
2015-07-08T09:40:52.9518630 info       [Thruway\RealmManager 7403] Realm "taxi" is using ManagerDummy
2015-07-08T09:40:52.9522710 debug      [Thruway\Realm 7403] Got Hello
2015-07-08T09:40:52.9573150 debug      [Thruway\Role\Broker 7403] Broker onMessage for {"type":"dummyTransport","transportAddress":"dummy"}: [16,8513655549993351,{},"wamp.metaevent.session.on_join",[{"realm":"taxi","authprovider":null,"authid":"anonymous","authrole":"anonymous","authroles":[],"authmethod":"anonymous","session":884382821620589,"role_features":{"publisher":{"features":{"subscriber_blackwhite_listing":true,"publisher_exclusion":true}},"subscriber":{"features":{}},"caller":{"features":{"caller_identification":true,"progressive_call_results":true}},"callee":{"features":{"caller_identification":true,"progressive_call_results":true}}}}]]
2015-07-08T09:40:52.9593930 debug      [Thruway\Peer\Client 7403] Client onMessage: [Thruway\Message\WelcomeMessage]
2015-07-08T09:40:52.9597960 info       [Thruway\Peer\Client 7403] We have been welcomed...
exception 'Exception' with message 'Session::abort called after we are authenticated' in /var/www/example/vendor/voryx/thruway/src/Thruway/AbstractSession.php:209
Stack trace:
#0 /var/www/example/vendor/voryx/thruway/src/Thruway/Peer/Router.php(134): Thruway\AbstractSession->abort(Array, 'wamp.error.unkn...')
#1 /var/www/example/vendor/voryx/thruway/src/Thruway/Transport/InternalClientTransport.php(70): Thruway\Peer\Router->onMessage(Object(Thruway\Transport\InternalClientTransport), Object(Thruway\Message\HelloMessage))
#2 /var/www/example/vendor/voryx/thruway/src/Thruway/ClientSession.php(115): Thruway\Transport\InternalClientTransport->sendMessage(Object(Thruway\Message\HelloMessage))
#3 /var/www/example/vendor/voryx/thruway/src/Thruway/Peer/Client.php(279): Thruway\ClientSession->sendMessage(Object(Thruway\Message\HelloMessage))
#4 /var/www/example/vendor/voryx/thruway/src/Thruway/Peer/Client.php(255): Thruway\Peer\Client->startSession(Object(Thruway\ClientSession))
#5 /var/www/example/vendor/voryx/thruway/src/Thruway/Transport/InternalClientTransportProvider.php(72): Thruway\Peer\Client->onOpen(Object(Thruway\Transport\InternalClientTransport))
#6 /var/www/example/vendor/voryx/thruway/src/Thruway/Peer/Router.php(176): Thruway\Transport\InternalClientTransportProvider->startTransportProvider(Object(Thruway\Peer\Router), Object(React\EventLoop\StreamSelectLoop))
#7 /var/www/example/app/commands/WebSocketServer.php(84): Thruway\Peer\Router->start()
#8 /var/www/example/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): WebSocketServer->fire()
#9 /var/www/example/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/example/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/example/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/example/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(WebSocketServer), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/example/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/example/artisan(59): Symfony\Component\Console\Application->run()
#15 {main}
```

**Comment by wkiril** [comment]
I just found the issue, it was totally on my part - the listen ports of the router and zmq where already in use by another router (which I am trying to replace using Thruway) Thank you for your time, @davidwdan

**Comment by Maelfyn** [comment]
> I'm glad that's working for you. You can further simplify that code by combining everything into one file and using the event emitter.
> 
> How you do it is up to you, but I thought I'd add this just in case someone else needs it:
> 
> PushServerCommand.php
> 
> ```
> 
> $loop   = \React\EventLoop\Factory::create();
> $pusher = new \Thruway\Peer\Client("realm1", $loop);
> 
> $pusher->on('open', function ($session) use ($loop) {
>     $context = new React\ZMQ\Context($loop);
>     $pull    = $context->getSocket(ZMQ::SOCKET_PULL);
>     $pull->bind('tcp://127.0.0.1:5555');
> 
>     $pull->on('message', function ($entry) use ($session) {
>         $entryData = json_decode($entry, true);
>         if (isset($entryData['category'])) {
>             $session->publish($entryData['category'], [$entryData]);
>         }
>     });
> });
> 
> $router = new Thruway\Peer\Router($loop);
> $router->addInternalClient($pusher);
> $router->addTransportProvider(new Thruway\Transport\RatchetTransportProvider("0.0.0.0", 7474));
> $router->start();
> ```

This is great. I think this is what I need, but I would like to clarify some details. Is this the PHP script that runs in a react loop? Is this the only code I need to handle for both client- and server-side push? Or do we also have to run a normal Thruway Server script in addition to a React loop-based push script?? 

Sorry. I get very confused with how server push works. Thanks for your help. Any additional documentation would be greatly appreciated.

**Comment by RyanMan56** [comment]
Thank you guys for helping me to avoid a situation like this in 2019:

![image](https://user-images.githubusercontent.com/2663541/51533193-03ab3880-1e3a-11e9-9826-324f0d150b7b.png)

**Comment by xbrunosousa** [comment]
How do you do that today? I was not successful trying the answers above (Laravel 7 + php 7.4)
